# Generated by Django 2.0.6 on 2018-07-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuG202_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timespans',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
