# Generated by Django 2.0.6 on 2018-10-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuG202_api', '0002_restaurant_timespans'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
