# Generated by Django 2.0.6 on 2018-12-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuG202_api', '0004_auto_20181204_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
