# Generated by Django 2.0.6 on 2018-12-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuG202_api', '0006_auto_20181204_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timespans',
            field=models.CharField(max_length=400),
        ),
    ]
